### ISSUE TITLE
XBMC Gotham 13 compatibility

### ISSUE THREAD

**Issue by fbradyirl** [PavelKuzub/service.3denabler.samsungtv#1]
Hi there,

Are there plans to make this compatible with XBMC 13? Let me know if you need me to test it. It currently doesn't switch my Samsung TV to 3D on Gotham.

/Finbarr

**Comment by PavelKuzub** [comment]
Hello Finbarr,

I tested on XBMC 13 alpha 10 and 11 and it worked with ES7500.
Can you please tell me what is the exact build of XBMC you are using? Also what is the model of your Samsung TV? I certainly would like you to test it. 
Thank you

Pavel

**Comment by fbradyirl** [comment]
Hi Pavel,

I will check when I get home, but I think it was this version that I
installed on my Raspberry Pi

OpenELEC-RPi.arm-devel-20140203195257-r17615-ge72843f.tar.bz2http://openelec.thestateofme.com/dev_builds/OpenELEC-RPi.arm-devel-20140203195257-r17615-ge72843f.tar.bz2

The TV is the following model: _UE32ES6300_

I am using XBMC to stream from my Vu PVR (using the Vu Plus PVR addon), and
when I switch to Sky 3D, I change mode in XBMC to SBS stereoscopic mode,
however, the TV must also be set to 3D mode (this doesn't happen
automatically with your plugin).

Regards
Finbarr

On 6 February 2014 14:57, PavelKuzub notifications@github.com wrote:

> Hello Finbarr,
> 
> I tested on XBMC 13 alpha 10 and 11 and it worked with ES7500.
> Can you please tell me what is the exact build of XBMC you are using? Also
> what is the model of your Samsung TV? I certainly would like you to test
> it.
> Thank you
> 
> Pavel
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/PavelKuzub/xbmc-addon-3denabler-samsungtv/issues/1#issuecomment-34330015
> .

## 

_Jabber_Call Mehttps://sjc-jabberc-ext.cisco.com/call/81384850@cisco.com?name=Finbarr%20Brady%20Cisco
browser-based
video chat.

**Comment by PavelKuzub** [comment]
Hello Finbarr,

Your case is interesting. I would like to take a look at the debug logs.

Can you please enable debug logging in XBMC, restart XBMC, make sure your TV is on and discovered by plugin, switch XBMC into SBS mode.
Then please archive and send me your xbmc.log to pavel.kuzub at gmail.com. Thank you

Pavel

**Comment by fbradyirl** [comment]
Sure, will do.

On 6 February 2014 15:59, PavelKuzub notifications@github.com wrote:

> Hello Finbarr,
> 
> Your case is interesting. I would like to take a look at the debug logs.
> 
> Can you please enable debug logging in XBMC, restart XBMC, make sure your
> TV is on and discovered by plugin, switch XBMC into SBS mode.
> Then please archive and send me your xbmc.log to pavel.kuzub at gmail.com.
> Thank you
> 
> Pavel
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/PavelKuzub/xbmc-addon-3denabler-samsungtv/issues/1#issuecomment-34337321
> .

## 

_Jabber_Call Mehttps://sjc-jabberc-ext.cisco.com/call/81384850@cisco.com?name=Finbarr%20Brady%20Cisco
browser-based
video chat.

**Comment by fbradyirl** [comment]
Hey there. 

I had a quick look at the log and your plugin doesn't load right as it is missing  the python plugin ssdp. Fails on import of that. 

I can try and install that python module and get back to you if that fails. 

Cheers

Finbarr
Kind regards,
Finbarr
—

**Comment by PavelKuzub** [comment]
Hello Finbarr,

Thank you for an update. The ssdp.py is located under lib folder of the plugin.
The code extends the path to include lib folder, to being able to include the module. It worked on my both Windows and Mac and I would like to make sure it works on Raspbery PI as well. Would like to see a log anyway. Thank you

Pavel

**Comment by PavelKuzub** [comment]
I have just noticed that the lib folder I was referring to was not included into Github as it matched default exclusion list. I have commited the lib folder now.
Please sync the code to your plugins folder and try again. Thank you for reporting this!

Pavel

**Comment by fbradyirl** [comment]
Great. I will try tomorrow night. Related: do you think it would be possible for a plugin to detect when the 3D mode is activated on the TV and in turn, activate sbs stereoscopic mode in the playing channel? If so, I might look into doing it...Kind regards,
Finbarr
—

**Comment by PavelKuzub** [comment]
Hello Finbarr, as far as I am aware Samsung TV firmware itself is not reporting the 3D mode to any external interface that you can query. Not that it does not exist.
However, this information is available for the Smart TV apps. It is for sure can be done if you add your code to run as a client on TV. The drawback is that you cannot have your application run automatically on TV after TV startup, unless you patch the firmware to run the code on startup, that is not a mainstream solution.

You may find these links helpful for your research:
http://developer.samsung.com/samsung-web-api/technical-docs/TV-Control
http://img-developer.samsung.com/onlinedocs/samsung_webapi_guide_public_1.0/html/index.html

**Comment by fbradyirl** [comment]
Hi Pavel,

I tried to install the updated addon this morning, but I got an error on
screen saying that the addon structure was wrong, and it didnt install.
Nothing in the log really, but I will forward that also to you.

Thanks for the info about the TV firmware, I will look into that...

/Finbarr

On 7 February 2014 01:47, PavelKuzub notifications@github.com wrote:

> Hello Finbarr, as far as I am aware Samsung TV firmware itself is not
> reporting the 3D mode to any external interface that you can query. Not
> that it does not exist.
> However, this information is available for the Smart TV apps. It is for
> sure can be done if you add your code to run as a client on TV. The
> drawback is that you cannot have your application run automatically on TV
> after TV startup, unless you patch the firmware to run the code on startup,
> that is not a mainstream solution.
> 
> You may find these links helpful for your research:
> http://developer.samsung.com/samsung-web-api/technical-docs/TV-Control
> 
> http://img-developer.samsung.com/onlinedocs/samsung_webapi_guide_public_1.0/html/index.html
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/PavelKuzub/xbmc-addon-3denabler-samsungtv/issues/1#issuecomment-34396737
> .

## 

_Jabber_Call Mehttps://sjc-jabberc-ext.cisco.com/call/81384850@cisco.com?name=Finbarr%20Brady%20Cisco
browser-based
video chat.

**Comment by fbradyirl** [comment]
Looks like the lib directory should be inside the resources directory, as outlined here:

http://wiki.xbmc.org/index.php?title=Add-on_structure#Directory_structure

I will try this later...

**Comment by PavelKuzub** [comment]
Hello Finbarr,

The lib folder should be located in the root of the plugin despite the wiki suggests to have it under resources. The script is expecting to read the module from there. It is not the reason for the error of the incorrect structure message.
There was a reason why the lib is in the root and the reason is to enable the ssdp to be used by other scripts.
At the moment if you add dependancy of another addon - XBMC will automatically add the lib folder of that addon to the path, so that you can import its modules. For whatever reason, the path is extended to the lib that is in the root of the addon rather than inside the resources dir.
I noticed this technique is used by other addons, so I sticked to what the real world use rather that is on the wiki.

The error message of the incorrect structure should be thrown if addon.xml is not found inside the addon zip.

I will be working on having a proper zip file to ease install. But at this moment, it has to be installed from the sources manually

**Comment by fbradyirl** [comment]
Hi Pavel,

Thanks for that. So I manually ftpd the files over to that folder and it worked. The plugin works pretty well, although sometimes it will randomly switch the TV into 3D mode even when nothing is playing. 

There doesn't seem to be any way for me to get stereoscopic mode to automatically kick in when Sky 3D is viewed. Everything works fine with recorded files (as long as they have 3DSBS in the file name). However, there seems to be no way to do this with a stream such as the ones coming from my Vu PVR. 
Kind regards,
Finbarr
—

**Comment by PavelKuzub** [comment]
Hello Finbarr,

Thank you for confirming that the addon works on your Raspberry PI.

I would like to clarify the randomness of stereo mode change you are referring to.
The addon is attempting to follow the stereoscopic mode of XBMC UI itself no matter if anything is played or not.
If you open System properties and change current stereoscopic mode of UI - addon will pick it up within 5 seconds and will change TV to the same 3D mode. Starting to play a 3D movie is only one of the triggers to change XBMC UI into stereoscopic mode.

Your problem is that you Vu PVR plugin is not able to detect the stereo of the stream and it is not triggering XBMC Stereoscopic Manager to change the Stereo mode. This is something outside the scope of my addon. Get the XBMC into stereoscopic mode and my addon will take it from there and get your TV into respective mode to comply with XBMC mode.
Untill you get your PVR plugin detecting stream to be a 3D source - you can map a key in XBMC to open a window with stereoscopic modes and change it from anywhere. My addon will pick it up. I have such a keymap on a remote and a keyboard - very conveniet. Let me know if you want me to share my keymap. Cheers

Pavel

**Comment by fbradyirl** [comment]
Hi Pavel,

Yes I get what you are saying and I agree with you 100%. 

The randomness is possibly because I'm using nightly builds of Openelec and stability might not be just there yet. 

I think the PVR author guys have not done much work around the area of auto detecting SBS content, as the demand isn't there. Not many people watch live 3D, and there is only one UK channel so far that is 3D. I've had a look at the code, but I am more of a python programmer than c++ as used in the core PVR plugins, so it would be a bit tricky for me. 

To be honest, if I had a key map set up, and used it along with your plugin, this is exactly what I want. E.g with one key press everything goes correct in xbmc settings and the TV. 

Cheers

Finbarr
—

**Comment by PavelKuzub** [comment]
Hello Finbarr,

This is how I have the keymap configured to have a one button 3D change on both XBMC and TV. My below  keymaps are simplified for this feature only. If you don't have any custom keymaps - these are good start. If you have any - then please merge.

So I have the list of stereoscopic modes assigned to the blue "D" button on the remote (D as a short for 3D - the closest similarity I could get). So once I press blue "D" button - a list of stereoscopic modes appear and I select either Over/Under or Side by Side and then 3D Enabler sends the keys to the TV.
I believe this is exactly what you want. Once you kick your PVR and start your 3D channel - press that new key and select Side by Side mode - XBMC will start drawing UI is SBS mode, your TV will switch to SBS in few seconds afterwards. Happiness :)

Another thought on the randomness - this happens when addon believe TV is in certain 3D mode while it is not. When there is a mismatch - things get messy. That is the reason why I added a setting in the options to specify what is the actual current 3D mode on the TV. Alternatively if it is not in sync - you can manually set TV into the same mode the addon believe it is.
This is because different key press sequences are required when you are in 3D mode or not.
If you don't use the 3D button on the remote directly and only use "D" keymap of XBMC - then it should not go wrong.

Keymap documentation:
http://wiki.xbmc.org/index.php?title=Keymap

XBMC/userdata/keymaps/keyboard.xml:
&lt;keymap&gt;
  &lt;global&gt;
    &lt;keyboard&gt;
      &lt;f1&gt;stereomode&lt;/f1&gt;
    &lt;/keyboard&gt;
  &lt;/global&gt;
&lt;/keymap&gt;

XBMC/userdata/keymaps/remote.xml:
&lt;keymap&gt;
  &lt;global&gt;
    &lt;remote&gt;
      &lt;blue&gt;stereomode&lt;/blue&gt;
    &lt;/remote&gt;
  &lt;/global&gt;
&lt;/keymap&gt;

**Comment by fbradyirl** [comment]
Hi Pavel,

Thanks so much for this! This is 90% what I want. 

Basically when I press blue now, I get the UI and TV to switch to 'SBS' mode in sync. However, for me, the video itself is still split in two, with no '3d' button in the xbmc 'now playing' UI. I still need to open the video prefs, scroll down to change stereoscopic mode, set it to SBS, exit that, scroll over to the new '3D' button, scroll up, and enable it. All in all, about 20 button presses. 

I might see if I can add that into my key maps somehow. I'll take a look. 

Cheers,
Kind regards,
Finbarr
—

**Comment by PavelKuzub** [comment]
Hello Finbarr,

PVR developers have to work to detect 3D channels. Gotham is barely in beta and 3D functionality is on it's way for adoption. 
I am filling one of the gaps in this puzzle. The remaining 10% you have to carry from PVR side :)

To save key presses - you may skip pressing D now and go straight to video properties, set video stereo mode and then enable it. TV will switch to SBS then. Maybe this will save you couple of key presses :)

I have release version 0.1.1 that should resolve addon structure issue from Github zip. Let me know if it works for you.

Pavel

**Comment by fbradyirl** [comment]
Hi Pavel,

I think there you're right about the PVR side. At the moment, the video stream comes to XBMC looking like a normal stream. However, I'm not sure if there is even a proper standard yet for naming a stream with 3D. E.g. like files with '3DSBS' in the name. I need to read up more on 3D streams.

"To save key presses - you may skip pressing D now and go straight to video properties, set video stereo mode and then enable it. TV will switch to SBS then."

< I wonder is there some way I can automate this? I might look into writing a plugin that will do all this with one click. 

Cheers,
Finbarr
